name: Run Tracker

on:
  schedule:
    - cron: "0 */2 * * *"   # alle 2 Stunden (UTC)
  workflow_dispatch: {}

permissions:
  contents: write   # erlaubt commit/push von state.json

concurrency:
  group: level-tracker
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          FORCE_ANNOUNCE_FIRST_RUN: "false"
          SEND_TEST_MESSAGE: "false"
        run: python bequiet_tracker_level.py

      - name: Commit state.json (if changed)
        run: |
          if [ -f state.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json || true
            git diff --staged --quiet || git commit -m "Update state.json"
            git push
          fi
