name: Run Tracker

on:
  schedule:
    - cron: "0 * * * *"   # jede volle Stunde
  workflow_dispatch:

permissions:
  contents: write   # erlaubt commit/push von state.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          FORCE_ANNOUNCE_FIRST_RUN: "true"   # sorgt für 1x Meldung der aktuellen Spieler
          SEND_TEST_MESSAGE: "true"          # zusätzliche Test-Nachricht „✅ Testlauf erfolgreich“
        run: python bequiet_tracker_level.py

      - name: Commit state.json (if changed)
        run: |
          if [ -f state.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json || true
            git diff --staged --quiet || git commit -m "Update state.json"
            git push
          fi
